#!/usr/bin/env php
<?php

include $_composer_autoload_path ?? __DIR__ . '/vendor/autoload.php';

use Panlatent\Translator\Command\ExtractCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new ExtractCommand());
$code = $application->run();
exit($code);